### ISSUE TITLE
[Bug]: Forked repository automatically launches `demo-build-distribution` (and fails)

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/ods-android#205]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

N/A

### OS Version

N/A

### App version

N/A

### Describe the issue

I have forked this repo in https://github.com/julien-deramond/ods-android. Each day, `demo-build-distribution` is run (source: https://github.com/julien-deramond/ods-android/actions/workflows/demo-build-distribution.yml) and fails.

### Expected Behavior

`demo-build-distribution` doesn't fail or is not launched for a fork (depending on what it does)

**Comment by julien-deramond** [comment]
It could be done like this:
```yml
jobs:
  build:
    runs-on: ubuntu-latest
   if: github.repository == 'Orange-OpenSource/ods-android'
```
